--전체 ROW를 n개씩 그룹 지을 때 -->CEIL()를 이용하자
SELECT 
      COL1
    , COL2
    , COL3
    , ROWNUM/4
    , CEIL(ROWNUM/4) --CEIL(n) 올림함수, 소수점을 가장 가까운 정수로 올림
  FROM (
    SELECT 'A1' AS COL1, 'B1' AS COL2, 'C1' AS COL3 FROM DUAL
    UNION ALL
    SELECT 'A2' AS COL1, 'B2' AS COL2, 'C2' AS COL3 FROM DUAL
    UNION ALL
    SELECT 'A3' AS COL1, 'B3' AS COL2, 'C3' AS COL3 FROM DUAL
    UNION ALL
    SELECT 'A4' AS COL1, 'B4' AS COL2, 'C4' AS COL3 FROM DUAL
    UNION ALL
    SELECT 'AA1' AS COL1, 'BB1' AS COL2, 'CC1' AS COL3 FROM DUAL
    UNION ALL
    SELECT 'AA2' AS COL1, 'BB2' AS COL2, 'CC2' AS COL3 FROM DUAL
    UNION ALL
    SELECT 'AA3' AS COL1, 'BB3' AS COL2, 'CC3' AS COL3 FROM DUAL
    UNION ALL
    SELECT 'AA4' AS COL1, 'BB4' AS COL2, 'CC4' AS COL3 FROM DUAL
    UNION ALL
    SELECT 'A1' AS COL1, 'B1' AS COL2, 'C1' AS COL3 FROM DUAL
    UNION ALL
    SELECT 'A2' AS COL1, 'B2' AS COL2, 'C2' AS COL3 FROM DUAL
    UNION ALL
    SELECT 'A3' AS COL1, 'B3' AS COL2, 'C3' AS COL3 FROM DUAL
    UNION ALL
    SELECT 'A4' AS COL1, 'B4' AS COL2, 'C4' AS COL3 FROM DUAL
    UNION ALL
    SELECT 'AA1' AS COL1, 'BB1' AS COL2, 'CC1' AS COL3 FROM DUAL
    UNION ALL
    SELECT 'AA2' AS COL1, 'BB2' AS COL2, 'CC2' AS COL3 FROM DUAL
    UNION ALL
    SELECT 'AA3' AS COL1, 'BB3' AS COL2, 'CC3' AS COL3 FROM DUAL
    UNION ALL
    SELECT 'AA4' AS COL1, 'BB4' AS COL2, 'CC4' AS COL3 FROM DUAL
)
;
